<?php
require_once __DIR__ . '/../core/db.php'; require_once __DIR__ . '/../core/functions.php'; require_once __DIR__ . '/../core/security.php'; require_once __DIR__ . '/../core/auth.php'; require_once __DIR__ . '/../core/rbac.php'; require_once __DIR__ . '/../core/branch_portal.php';
$branchId=require_portal_branch_id(); $branch=portal_branch_row($branchId); $customCss=setting('custom_css','');
$start=$_GET['start'] ?? date('Y-m-d'); $end=$_GET['end'] ?? date('Y-m-d');
$startDt=$start.' 00:00:00'; $endDt=(new DateTimeImmutable($end))->modify('+1 day')->format('Y-m-d 00:00:00');
$stmt=db()->prepare("SELECT s.transaction_code, MIN(s.sold_at) sold_at, COUNT(*) item_count, SUM(s.qty) qty, SUM(s.total) total, s.payment_method, COALESCE(s.payment_channel_name,s.payment_bank,'') channel, u.name cashier FROM sales s LEFT JOIN users u ON u.id=s.created_by WHERE s.branch_id=? AND s.sold_at>=? AND s.sold_at<? AND s.return_reason IS NULL AND s.is_active_revision=1 GROUP BY s.transaction_code, s.payment_method, channel, u.name ORDER BY sold_at DESC LIMIT 500");
$stmt->execute([$branchId,$startDt,$endDt]); $rows=$stmt->fetchAll(PDO::FETCH_ASSOC); $sum=0; foreach($rows as $r){$sum+=(float)$r['total'];}
function navc($a){$items=['index.php'=>'Dashboard','sales.php'=>'Penjualan','shifts.php'=>'Shift','stock.php'=>'Stok']; echo '<div class="card" style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px">'; foreach($items as $u=>$l){echo '<a class="'.e($a===$u?'btn':'btn secondary').'" href="'.e(base_url('cabang/'.$u)).'">'.e($l).'</a>'; } echo '</div>';}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Penjualan Cabang</title><link rel="stylesheet" href="<?php echo e(asset_url('assets/app.css')); ?>"><style><?php echo $customCss; ?></style></head><body><div class="main" style="margin:0"><div class="content"><h2>Penjualan Cabang: <?php echo e($branch['branch_name'] ?? ''); ?></h2><?php navc('sales.php'); ?><div class="card"><form method="get" style="display:flex;gap:10px;align-items:end;flex-wrap:wrap"><div class="row"><label>Dari</label><input type="date" name="start" value="<?php echo e($start); ?>"></div><div class="row"><label>Sampai</label><input type="date" name="end" value="<?php echo e($end); ?>"></div><button class="btn">Filter</button></form><h3>Total: Rp <?php echo e(format_money($sum)); ?></h3><div class="table-wrap"><table><thead><tr><th>Waktu</th><th>Kode</th><th>Item</th><th>Qty</th><th>Pembayaran</th><th>Kasir</th><th>Total</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?php echo e($r['sold_at']); ?></td><td><?php echo e($r['transaction_code']); ?></td><td><?php echo e((string)$r['item_count']); ?></td><td><?php echo e((string)$r['qty']); ?></td><td><?php echo e(trim($r['payment_method'].' '.$r['channel'])); ?></td><td><?php echo e($r['cashier'] ?? '-'); ?></td><td>Rp <?php echo e(format_money($r['total'])); ?></td></tr><?php endforeach; if(!$rows): ?><tr><td colspan="7">Belum ada penjualan pada periode ini.</td></tr><?php endif; ?></tbody></table></div></div></div></div></body></html>
