<?php
$lock = __DIR__ . '/install.lock'; $lockAlt = __DIR__ . '/LOCK';
if (file_exists($lock) || file_exists($lockAlt)) { header('Location: ../adm.php'); exit; }
function h($s){ return htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8'); }
$err=''; $ok='';
function adena_sql_statements(string $sql): array {
  $sql=preg_replace('/^\xEF\xBB\xBF/','',$sql); $out=[]; $buf=''; $q=null; $esc=false; $lc=false; $bc=false; $n=strlen($sql);
  for($i=0;$i<$n;$i++){ $ch=$sql[$i]; $nx=$i+1<$n?$sql[$i+1]:'';
    if($lc){ if($ch==="\n")$lc=false; continue; } if($bc){ if($ch==='*'&&$nx==='/'){$bc=false;$i++;} continue; }
    if($q!==null){ $buf.=$ch; if($esc)$esc=false; elseif($ch==='\\')$esc=true; elseif($ch===$q)$q=null; continue; }
    if($ch==='-'&&$nx==='-'){$lc=true;$i++;continue;} if($ch==='/'&&$nx==='*'){$bc=true;$i++;continue;} if($ch==='#'){$lc=true;continue;}
    if($ch==="'"||$ch==='"'||$ch==='`'){$q=$ch;$buf.=$ch;continue;} if($ch===';'){ $st=trim($buf); $buf=''; if($st!==''&&stripos($st,'DELIMITER')!==0)$out[]=$st; continue; } $buf.=$ch;
  } $st=trim($buf); if($st!=='')$out[]=$st; return $out;
}
if($_SERVER['REQUEST_METHOD']==='POST'){
  $app_name=trim($_POST['app_name']??'Adena POS Belitung'); $branch_name=trim($_POST['branch_name']??'Belitung'); $branch_code=strtoupper(trim($_POST['branch_code']??'BLT'));
  $base_url=rtrim(trim($_POST['base_url']??''),'/'); $db_host=trim($_POST['db_host']??'127.0.0.1'); $db_port=trim($_POST['db_port']??'3306'); $db_name=trim($_POST['db_name']??''); $db_user=trim($_POST['db_user']??'root'); $db_pass=(string)($_POST['db_pass']??'');
  $admin_username=trim($_POST['admin_username']??'admin'); $admin_name=trim($_POST['admin_name']??'Administrator'); $admin_pass1=(string)($_POST['admin_pass1']??''); $admin_pass2=(string)($_POST['admin_pass2']??'');
  try{ if($app_name===''||$branch_name===''||$branch_code===''||$base_url===''||$db_name==='') throw new Exception('Nama aplikasi, cabang, kode cabang, Base URL, dan database wajib diisi.'); if($admin_pass1===''||$admin_pass1!==$admin_pass2) throw new Exception('Password admin tidak cocok.');
    $dump=__DIR__.'/../db/adena_latest_single_belitung.sql'; if(!is_file($dump)) throw new Exception('File database terbaru tidak ditemukan: /db/adena_latest_single_belitung.sql');
    $pdo=new PDO("mysql:host={$db_host};port={$db_port};charset=utf8mb4",$db_user,$db_pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
    $safeDb=str_replace('`','``',$db_name); $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$safeDb}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"); $pdo->exec("USE `{$safeDb}`");
    foreach(adena_sql_statements(file_get_contents($dump)) as $stmt){ $pdo->exec($stmt); }
    $pdo->prepare("INSERT INTO branches (id,branch_code,branch_name,unit_type,is_kitchen,is_active,sort_order) VALUES (1,?,?, 'branch',0,1,0) ON DUPLICATE KEY UPDATE branch_code=VALUES(branch_code), branch_name=VALUES(branch_name), unit_type='branch', is_kitchen=0, is_active=1")->execute([$branch_code,$branch_name]);
    $pdo->exec("UPDATE branches SET is_active=0 WHERE id<>1"); try{$pdo->exec("UPDATE api_tokens SET branch_id=1 WHERE branch_id IS NULL OR branch_id<>1");}catch(Throwable $e){}
    $pdo->prepare("INSERT INTO users (username,name,role,password_hash) VALUES (?,?, 'owner', ?) ON DUPLICATE KEY UPDATE name=VALUES(name), role='owner', password_hash=VALUES(password_hash)")->execute([$admin_username,$admin_name,password_hash($admin_pass1,PASSWORD_DEFAULT)]);
    $set=$pdo->prepare("INSERT INTO settings (`key`,`value`) VALUES (?,?) ON DUPLICATE KEY UPDATE `value`=VALUES(`value`)"); foreach(['active_branch_id'=>'1','branch_mode'=>'single','branch_name'=>$branch_name,'branch_code'=>$branch_code,'store_name'=>$app_name,'store_subtitle'=>'Makanan Khas Belitung','api_topology'=>'branch_to_branch,branch_to_kitchen,branch_to_backoffice,kitchen_to_backoffice'] as $k=>$v){$set->execute([$k,$v]);}
    $config=['app'=>['name'=>$app_name,'base_url'=>$base_url,'branch_name'=>$branch_name,'branch_code'=>$branch_code,'branch_mode'=>'single'],'db'=>['host'=>$db_host,'port'=>$db_port,'name'=>$db_name,'user'=>$db_user,'pass'=>$db_pass,'charset'=>'utf8mb4'],'security'=>['session_name'=>'ADENAPOSSESS']]; file_put_contents(__DIR__.'/../config.php',"<?php\nreturn ".var_export($config,true).";\n"); @mkdir(__DIR__.'/../private_uploads',0755,true); @mkdir(__DIR__.'/../uploads',0755,true); file_put_contents($lock,'installed '.date('c')); $ok="Instalasi selesai. Sistem aktif sebagai single cabang {$branch_name} ({$branch_code}).";
  }catch(Throwable $e){$err=$e->getMessage();}
}
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Installer Adena POS Belitung</title><style>body{font-family:system-ui,-apple-system,Segoe UI,sans-serif;background:#f1f5f9;margin:0;color:#0f172a}.wrap{max-width:760px;margin:40px auto;background:#fff;border-radius:18px;padding:24px;box-shadow:0 10px 30px #0f172a22}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}label{font-weight:700;font-size:13px}input{width:100%;padding:11px;border:1px solid #cbd5e1;border-radius:12px;box-sizing:border-box}.full{grid-column:1/-1}.btn{background:#0f172a;color:#fff;border:0;border-radius:12px;padding:12px 18px;font-weight:800;cursor:pointer}.note{background:#e0f2fe;border:1px solid #7dd3fc;color:#075985;padding:12px;border-radius:12px;margin-bottom:18px}.err{background:#fee2e2;color:#991b1b;padding:12px;border-radius:12px}.ok{background:#dcfce7;color:#166534;padding:12px;border-radius:12px}@media(max-width:720px){.grid{grid-template-columns:1fr}.wrap{margin:12px}}</style></head><body><div class="wrap"><h1>Installer Adena POS Belitung</h1><div class="note"><b>Mode:</b> single cabang per domain. Default: <b>Cabang Belitung</b>. Cabang, dapur, dan backoffice lain disiapkan sebagai instalasi terpisah yang saling terhubung lewat API.</div><?php if($err): ?><p class="err"><?php echo h($err); ?></p><?php endif; ?><?php if($ok): ?><p class="ok"><?php echo h($ok); ?> <a href="../adm.php">Masuk admin</a></p><?php endif; ?><form method="post"><div class="grid"><div><label>Nama Aplikasi</label><input name="app_name" value="Adena POS Belitung"></div><div><label>Base URL</label><input name="base_url" placeholder="https://adena.co.id"></div><div><label>Nama Cabang</label><input name="branch_name" value="Belitung"></div><div><label>Kode Cabang</label><input name="branch_code" value="BLT"></div><div><label>DB Host</label><input name="db_host" value="127.0.0.1"></div><div><label>DB Port</label><input name="db_port" value="3306"></div><div><label>DB Name</label><input name="db_name"></div><div><label>DB User</label><input name="db_user" value="root"></div><div class="full"><label>DB Password</label><input name="db_pass" type="password"></div><div><label>Admin Username</label><input name="admin_username" value="admin"></div><div><label>Admin Name</label><input name="admin_name" value="Administrator"></div><div><label>Password Admin</label><input name="admin_pass1" type="password"></div><div><label>Ulangi Password</label><input name="admin_pass2" type="password"></div><div class="full"><button class="btn" type="submit">Install Database Terbaru</button></div></div></form></div></body></html>
