<?php
require_once __DIR__ . '/../core/db.php'; require_once __DIR__ . '/../core/functions.php'; require_once __DIR__ . '/../core/security.php'; require_once __DIR__ . '/../core/auth.php'; require_once __DIR__ . '/../core/rbac.php'; require_once __DIR__ . '/../core/branch_portal.php';
start_secure_session(); require_login(); ensure_branch_price_schema(); $customCss=setting('custom_css','');
$kitchens = table_exists('stock_locations') ? db()->query("SELECT * FROM stock_locations WHERE location_type='kitchen' AND is_active=1 ORDER BY location_name")->fetchAll(PDO::FETCH_ASSOC) : [];
$locId=(int)($_GET['location_id'] ?? ($kitchens[0]['id'] ?? 0));
$stock=[]; $transfers=[];
if ($locId>0) {
  try { $stmt=db()->prepare("SELECT p.name, p.category, p.base_unit, COALESCE(SUM(sl.qty_in-sl.qty_out),0) qty FROM products p LEFT JOIN stock_ledger sl ON sl.product_id=p.id AND sl.location_id=? WHERE COALESCE(p.track_stock,1)=1 GROUP BY p.id ORDER BY p.name LIMIT 500"); $stmt->execute([$locId]); $stock=$stmt->fetchAll(PDO::FETCH_ASSOC); } catch(Throwable $e) {}
  if (table_exists('stock_transfers')) { try { $stmt=db()->prepare("SELECT st.*, fl.location_name from_name, tl.location_name to_name FROM stock_transfers st LEFT JOIN stock_locations fl ON fl.id=st.from_location_id LEFT JOIN stock_locations tl ON tl.id=st.to_location_id WHERE st.from_location_id=? OR st.to_location_id=? ORDER BY st.created_at DESC LIMIT 50"); $stmt->execute([$locId,$locId]); $transfers=$stmt->fetchAll(PDO::FETCH_ASSOC); } catch(Throwable $e) {} }
}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Portal Dapur</title><link rel="stylesheet" href="<?php echo e(asset_url('assets/app.css')); ?>"><style><?php echo $customCss; ?></style></head><body><div class="main" style="margin:0;max-width:1200px"><div class="content"><h2>Portal Dapur</h2><div class="card" style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px"><a class="btn" href="<?php echo e(base_url('dapur/index.php')); ?>">Dashboard Dapur</a><a class="btn secondary" href="<?php echo e(base_url('admin/production.php')); ?>">Produksi</a><a class="btn secondary" href="<?php echo e(base_url('admin/purchase_raw_material.php')); ?>">Pembelian dari Admin</a><a class="btn secondary" href="<?php echo e(base_url('admin/logout.php')); ?>">Logout</a></div>
<div class="card"><form method="get" style="display:flex;gap:10px;align-items:end;flex-wrap:wrap"><div class="row"><label>Lokasi Dapur</label><select name="location_id" onchange="this.form.submit()"><?php foreach($kitchens as $k): ?><option value="<?php echo e((string)$k['id']); ?>" <?php echo ((int)$k['id']===$locId)?'selected':''; ?>><?php echo e($k['location_name']); ?></option><?php endforeach; ?></select></div><noscript><button class="btn">Pilih</button></noscript></form><?php if(!$kitchens): ?><p>Lokasi dapur belum dibuat di stock_locations.</p><?php endif; ?></div>
<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(360px,1fr));gap:12px;margin-top:12px"><div class="card"><h3>Stok Dapur</h3><div class="table-wrap"><table><thead><tr><th>Produk</th><th>Kategori</th><th>Qty</th></tr></thead><tbody><?php foreach($stock as $s): ?><tr><td><?php echo e($s['name']); ?></td><td><?php echo e($s['category'] ?? '-'); ?></td><td><?php echo e(format_qty($s['qty'],$s['base_unit'])); ?></td></tr><?php endforeach; if(!$stock): ?><tr><td colspan="3">Belum ada data stok dapur.</td></tr><?php endif; ?></tbody></table></div></div><div class="card"><h3>Transfer Terakhir</h3><div class="table-wrap"><table><thead><tr><th>No</th><th>Dari</th><th>Ke</th><th>Status</th></tr></thead><tbody><?php foreach($transfers as $t): ?><tr><td><?php echo e($t['transfer_no']); ?></td><td><?php echo e($t['from_name'] ?? '-'); ?></td><td><?php echo e($t['to_name'] ?? '-'); ?></td><td><?php echo e($t['status']); ?></td></tr><?php endforeach; if(!$transfers): ?><tr><td colspan="4">Belum ada transfer.</td></tr><?php endif; ?></tbody></table></div></div></div>
</div></div></body></html>
